### ISSUE TITLE
FIXED: Testing problems today

### ISSUE THREAD

**Issue by jee7s** [frc6357/robot_code#22]
Call it an undocumented error or whatver, but the reset() function on a PID controller also disables it. Since the pass at the code we were testing didn't re-enable it, nothing worked. There are a lot of comments in the latest position_and_velocity_control branch, but it all really amounts to a single line in VelocityControlledDrivetrainSide to fix the problem.

Fix is checked in, please pull at your earliest convenience.

**Comment by hoo761** [comment]
Awesome, I will pull right now
