### ISSUE TITLE
Delete project file that is not used.

### ISSUE THREAD

**Issue by jee7s** [frc6357/robot_code#5]
Please identify the project file in the repository and remove it. I believe the one under the SpringKonstant folder is the appropriate one to use, but I wasn't sure. Let's try to avoid the ambiguous nature of having two project files. Once the repo has been changed to only have the one project file present, We'll move the project up to the top level.

**Comment by hoo761** [comment]
I removed all the old project files, and the SpringKonstant file is up to date

**Comment by jee7s** [comment]
Please double check the root folder. The repository is showing a .project file there.

**Comment by hoo761** [comment]
Everything we do not need is gone. 1c60b53

**Comment by jee7s** [comment]
This looks done based on my read of the code.
