### ISSUE TITLE
Move autonomous code into java

### ISSUE THREAD

**Issue by jee7s** [frc6357/robot_code#8]
We had a good plan on how to approach auto, so let's get those basic elements into java

**Comment by hoo761** [comment]
In the autonomous, instead of while loops can I use recursion where the method will call its self, or will that stop the robot like while loops.

**Comment by jee7s** [comment]
Recursion is also a bad idea, because you can end up too deep in the call stack. Remember that there is a while loop as part of Robot.java. So the loop happens out there, and you just call your update function inside that.

We can discuss more at next meeting.

**Comment by jee7s** [comment]
Closing as this is stale. Auton still needs work, but it's in Java.
